import { initAccordion } from "./modules/accordion.js";
import { initDropDownMenu } from "./modules/dropdown-menu.js";
import { initFetchAnimais } from "./modules/fetch-animais.js";
import { initFetchBitcoin } from "./modules/fetch-bitcoin.js";
import { initFuncionamento } from "./modules/funcionamento.js";
import { initMenuMobile } from "./modules/menu-mobile.js";
import { initModal } from "./modules/modal.js";
import { initAnimacaoScroll } from "./modules/scroll-animacao.js";
import { initScrollSuave } from "./modules/scroll.suave.js";
import { initTabNav } from "./modules/tab-nav.js";
import { initToolTip } from "./modules/tooltip.js";

initTabNav();
initAccordion();
initScrollSuave();
initAnimacaoScroll();
initModal();
initToolTip();
initDropDownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();